version: '2'
services:

  # Nginx
  nginx:
    build: ./deploy/nginx
    image: jsanweb/nginx1
    container_name: nginx
    restart: always
    links:
      - app
    ports:
      - "80:80"

  # Application
  app:
    build: ./app
    image: jsanweb/app1
    container_name: app
    restart: always
    volumes:
      - ./app:/app
    volumes_from:
      - data

  # Data
  data:
    build: ./data
    image: jsanweb/data1
    container_name: data
    volumes:
      - ./data:/var/lib/appdata
